@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(stud, "Student", "Student of the university viewing the calendar")
Person(asso, "Student Association", "Student Association creating events")

Container(sys, "Student Calendar","React, ASP.NET Core", "The system developed for this project")
Container(ria, "RIA's Webpage","Wordpress", "Ria's webpage where the calendar will be embedded")
Rel(stud, sys, "Views")
Rel(asso, sys, "Creates events")
Rel(ria,sys, "Hosts")
@enduml
