@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(stud, "Student", "Student of the university viewing the calendar")
Person(asso, "Student Association", "Student Association creating events")

Container(sys, "Student Calendar","React", "The system developed for this project")
Container(ria, "RIA's Webpage","Wordpress", "The webpage of the RIA where the calendar will be embedded. This webpage is hosted on the servers of a firm called Aveo")
ContainerDb(aveoDB,"Aveo's Database","MsSQL", "The database of Aveo where RIA stores their users. And where events are stored")
Rel(stud, sys, "Views")
Rel(asso, sys, "Creates events")
Rel(ria,sys, "Hosts")
Rel(sys, aveoDB, "Stores events")

@enduml
