@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(stud, "Student", "A student looking for an overview of the events on campus")
Person(asso, "StudentAssociation", "Student Association creating events")

System_Boundary(frontend, "Front-end Application", "React", "Front-end application for the Student Calendar") {
    Container(AccountPage, "AccountPage", "Page for managing user accounts")
    Container(AddEventPage, "AddEventPage", "Page for adding new events")
    Container(CalendarPage, "CalendarPage", "Page for displaying the calendar")
    Container(EventPage, "EventPage", "Page for displaying event details")
    Container(HomePage, "HomePage", "Main landing page of the application")
    Container(LoginPage, "LoginPage", "Page for user authentication")
    Container(VerifyPage, "VerifyPage", "Page for verifying user accounts")
}

Container(be, "Back-end API", "ASP.NET Core", "Back-end API for the Student Calendar")
Container(db, "Database", "PostgreSQL", "The AWS database where the events and users are stored")

Rel(stud, frontend, "Views")
Rel(asso, frontend, "Creates events")
Rel(be, db, "Stores events")
Rel(frontend, be, "Gets/sends data")

Rel(CalendarPage, be, "Gets events")
Rel(EventPage, be, "Gets events")
Rel(HomePage, be, "Gets events")
@enduml
