@startuml ServicesClassDiagram

class ChatGPTService {

}

class EmailReputationService {
}

class EmailService {
}

class EncryptionService {
  
}

class EventService {
       +existingMethod(): void 
    +<color:red>MethodForAddedUS(): void 
    +<color:red>MethodForAddedUS(): void 

}

class EventTagService {
 
}

class EventUserService {

}

class ReCaptchaService {
}

class RoleService {

}

class TagService {
   
}

class UserService {
   
}

@enduml
