@startuml FrontEndClassDiagram
class HomePage {
    
    +existingMethod(): void 
    +<color:red>MethodForAddedUS(): void 
    +<color:red>MethodFromChild(): void 
    
}
class CalendarPage {
}
class EventPage {
}
class AddEventPage {
}
class VerifyPage {
}
class AccountPage {
}
class LoginPage {
    
}

@enduml
