@startuml test
left to right direction
skinparam packageStyle rect
actor Student as g
actor StudentAssociation as fc
actor reCAPTCHA as rc
actor CalendarServices as gc
actor Facebook as fb
actor brevo as b
actor ChatGPT as cg

package Studieforeningskalenderen {
  usecase "EP 1 See Events" as UC1
  usecase "EP 2 Login" as UC2
  usecase "EP 3 Create Events" as UC3
  usecase "EP 4 Import Events" as UC4
}

g -right- UC1
fc -- UC2
fc -- UC3 
fc -- UC4 
g -- UC2
UC1 -- gc
UC4 -- fb
UC2 -- rc 
UC2 -- b
UC3 -- cg
UC2 -[hidden]- gc
gc -[hidden]- rc
gc -[hidden]- gc






@enduml