@startuml "System sequence diagram for UC1 and UC2"
title System Sequence Diagram for UC1, UC2 and UC4
actor User
participant FrontEnd
participant BackEnd
participant Database

User -> FrontEnd: Open page
FrontEnd -> BackEnd: Get Important events
activate BackEnd
BackEnd -> Database: Get Events
BackEnd --> FrontEnd: Event data
deactivate BackEnd
FrontEnd -> FrontEnd: Cache Important events
FrontEnd --> User: Page visible
FrontEnd -> BackEnd: Get All events
activate BackEnd
BackEnd -> Database: Get Events
BackEnd --> FrontEnd: Event data
deactivate BackEnd
FrontEnd --> User: Events visible

User -> FrontEnd: Click on event
FrontEnd -> BackEnd: Get Event details
activate BackEnd
BackEnd -> Database: Get Event details
BackEnd --> FrontEnd: Event details
deactivate BackEnd
FrontEnd --> User: Event details page

@enduml
