@startuml "US5 and US6 System"
title System Sequence Diagram for US5 and US6
actor Student as User
participant "Front-End" as FrontEnd 
participant "Back-End"  as BackEnd
database Database
User -> FrontEnd: Opens the page
note left
  User Story 5 and 6.
prerequisite: User has logged in previously
end note
activate FrontEnd

FrontEnd -> BackEnd: Request relevant Events 
activate BackEnd
FrontEnd -> BackEnd: User ID
BackEnd -> Database: Get User Information
activate Database
Database -> BackEnd: User Information
deactivate Database
BackEnd -> Database: Get relevant Events Based off User Information
activate Database
Database -> BackEnd: Relevant Events
deactivate Database
BackEnd -> FrontEnd: Relevant Events
deactivate BackEnd
FrontEnd -> User: Start page View with relevant Events
deactivate FrontEnd

@enduml
