@startuml FrontEndClassDiagram
class HomePage {
    - 
    - searchText: String
    ~ events : Query
    ~ tags : Query
    --
    + PopularEvents
    + EventsSlider
    + EventCard
    + SideBar
    + Tags 
    + SelectedTags
}

class App {
    -isLoggedIn : Boolean
    ~validateSession : Query
        --
    + <color:blue>NavigationBar
    + ToggleSlider
    + <color:blue>Alerts
}
class CalendarPage {
    ~ events : Query 
    --
    + Calendar
    + Monthly
    + Weekly
    + Daily
    + DayEventModal    
}
class EventPage {
    -Image : Img
    -Event : Event
    ~addSelfToEvent : Mutation
    --
    + DateAndTimeBox
    + AddToCalendarButton
    + LocationBox
}
class LoginPage {
    ~ register : Mutation
    ~ login : Mutation
    ~ changePassword : Mutation
    --
    +Register
    +reCaptha
    +Login
    +Password
    +ForgotPassword
    }
    class VerifyPage {
    ~ verifyUser : Mutation
    ~ resendRegistrationVerificationEmail : Mutation
    ~ sendForgotPasswordVerificationEmail : Mutation
    --
}
class AccountPage {
    ~ signOut : Mutation
    ~ userInfo : Query
    ~ updateUser : Query
    ~ deleteUser : Mutation
    --
    +reCaptha
    +accountForm
    +DeleteUserModal
}
class AddEventPage {
    ~ <color:red>tags: Query
    ~ <color:red>isAdminOrUnion: Query
    ~ <color:red>addEvent : Mutation
    --
    +<color:red>addEventForm
}

App*-- HomePage 
App*-- CalendarPage   
App*-- LoginPage
App*-- AccountPage
App*-- VerifyPage
App*-- AddEventPage
HomePage-- EventPage
CalendarPage-- EventPage

legend
    |= Example  |= Description |
    |        ○ | A Component |
    |        □ | A Variable/UseState |
    |        <size:11>△ | Query or Mutation |
    |<color:red> Red text | Newly added|
    |<color:blue> Blue text | Updated |
endlegend
@enduml






