@startuml

class EventService {
    +  GetEvents(sorting, tags, searchText)     
    +  <color:red>CreateEvent(input)

}
EventService --> EventUserService

class UserService {
    + VerifyUser(emailAddress, token)
    + CreateUser(input) 
    + Login(loginInput) 
    + SignInAsync(user, roles, httpContext, rememberMe) 
    + ChangePassword(emailAddress, verificationCode, password, reCaptcha)
}

class ReCaptchaService {
    + ValidateReCaptcha(recaptcha) 
}
UserService --> ReCaptchaService

class EventUserService {
    + AddSelfToEvent(input) 
    + AddUserToEventInput(eventId, username, isAdmin)
}

class EmailService {
    + SendRegisterVerificationEmail(email, userId, firstName) 

    + SendForgotPasswordVerificationEmail(email, reCaptchaToken)

}
EmailService --> EncryptionService

class EmailReputationService {
    + CheckReputation(emailAddress) 

}
EmailService --> EmailReputationService

class UserRoleService {
    + GrantRoleToUser(input) 
}
UserService --> UserRoleService
class RoleService {
    + GetRolesById(roleIds) 
}
UserService --> RoleService

class EncryptionService {
    + Encrypt(plainText) 
    + Decrypt(cipherText) 
}
UserService --> EncryptionService

class TagService {
    +  <color:red>CreateTags(input)
}
class EventTagService {
    +  <color:red>AttachTagsToEvent(eventId,tags)
}
EventService --> TagService
EventService --> EventTagService

@enduml
