@startuml FrontEndClassDiagram
class HomePage {
    - 
    - sortPopular : useState
    ~ events : Query 
    --
    + PopularEvents: Component
    + EventsSlider: Component
    + SideBar: Component
}

class App {
    - changeSorting : Function
    - setSearchText : Function
    - addTag : Function
    - toggleSwitch : Function
    - HandleGQLSuccess : Function
    - HandleGQLError : Function
    - <color:red> ValidateCreateUserInput : Function
    --
    + <color:blue>NavBar: Component
    + Redux: Component
    + Alert: Component
    }
class CalendarPage {
    - events : Query
    --
    + Calendar: Component
    + Monthly: Component
    + Weekly: Component
    + Daily: Component
    + Select: Component
    + Navigate: Component
    + DayEventModal: Component

}
class EventPage {
    -Image : Img
    -Event : Event
     ~addSelfToEvent: Mutation
    --
    + DateAndTimeBox : Component
    + LocationBox : Component
    + AddToCalendar : Component
}
class LoginPage {
    ~ <color:red>createUser : Mutation
    --
    +<color:red>Register: Component
    }
    class VerifyPage {
    ~ <color:red>verifyUser : Mutation
    --
}

App*-- HomePage    
App*-- CalendarPage  
App*-- LoginPage
App*-- VerifyPage
CalendarPage-- EventPage 
HomePage-- EventPage
legend
    |= Example  |= Description |
    |        ○ | A Component |
    |        □ | A Variable/Function |
    |        <size:11>△ | Query or Mutation |
    |<color:red> Red text | Newly added|
    |<color:blue> Blue text | Updated |
endlegend
@enduml

class EventPage {
}
class AddEventPage {
}
class VerifyPage {
}
class AccountPage {
}
class LoginPage {
    }
