@startuml FrontEndClassDiagram
class HomePage {
    - sortPopular : useState
    - setEventCount : useState
    ~ events : Query 
    --
    + PopularEvents: Component
    + EventsSlider: Component
}



class App {
    - changeSorting : Function
    --
    + NavBar: Component
    + Redux: Component
    + <color:red>Router: Component
    + <color:red>Alert: Component
    }

class CalendarPage {
    - <color:red>events : Query
    --
    + <color:red>Calendar: Component
    + <color:red>Monthly: Component
    + <color:red>Weekly: Component
    + <color:red>Daily: Component
    + <color:red>Select: Component
    + <color:red>Navigate: Component
}

App*-- HomePage    
App*-- CalendarPage   

class EventPage {
}
class AddEventPage {
}
class VerifyPage {
}
class AccountPage {
}
class LoginPage {
    }

legend
    |= Example  |= Description |
    |        ○ | A Component |
    |        □ | A Variable/Function |
    |        <size:11>△ | Query or Mutation |
    |<color:red> Red text | Newly added|
    |<color:blue> Blue text | Updated |
endlegend
@enduml
