@startuml "System Sequence Diagram for Register Flow"
title Backend Application Sequence Diagram for US11 Reset password

participant "Frontend" as fe #LightGreen
participant "EmailService" as es
participant "UserService" as us
participant "ReCaptchaService" as rs
participant "EmailReputationService" as ers
participant "EncryptionService" as en
database "Database" as db
participant "reCAPTCHA" as reCap #PaleVioletRed
participant "Brevo" as brev #PaleVioletRed



fe -> reCap: get reCAPTCHA-token
activate fe  
activate reCap
reCap --> fe: token
deactivate reCap
fe -> es: SendForgotPasswordVerificationEmail(email:string, token:string)
activate es
es -> rs: validateReCaptcha(token:string)
activate rs
rs -> reCap: validate token
activate reCap
reCap --> rs: reCaptchaVerified:boolean
deactivate reCap
rs --> es: reCaptchaVerified:boolean
deactivate rs

es-> ers: CheckReputation(email:string)
activate ers
ers --> es: hasBadReputation:boolean
deactivate ers
es -> en: Encrypt(userId:string)
activate en
note right of en
Encrypts the userId to create 
a verification code/token
end note
en --> es: token:string
deactivate en
es ->brev: send email
activate brev
brev --> es: email sent
deactivate brev
es --> fe: response
deactivate es

fe -> us: ChangePassword(email:string, token:string password:string, reCaptcha:string)
activate us
us -> en: Decrypt(token:string)
activate en
en --> us: userId:string
deactivate en
us -> db: update user with new password
activate db
db --> us: updated
deactivate db
us --> fe: response
deactivate us
@enduml
