@startuml "System Sequence Diagram for Register Flow"
title Frontend application  Sequence Diagram for US9 Register a user
actor User as user

participant "App" as App
participant "HomePage" as HomePage
participant "LoginPage" as LoginPage

participant "VerifyPage" as VerifyPage
participant "AccountPage" as AccountPage
participant "Backend" as be #LightGreen
participant "reCAPTCHA" as reCap #PaleVioletRed
participant "Email" as em #PaleVioletRed

user -> App: click on "Login"
activate App
App -> LoginPage: navigate(/Login)
deactivate App
activate LoginPage
LoginPage --> user: Display Register-component
deactivate LoginPage
user -> LoginPage: Fill out Register-form
user -> LoginPage: press "Register"
activate LoginPage
LoginPage -> App: ValidateCreateUserInput(data.createUserInput, data.confirmPassword):alert[]

LoginPage -> reCap: get reCAPTCHA-token
activate reCap
reCap --> LoginPage: token
deactivate reCap
LoginPage -> be: Create user mutation
activate be
be -> LoginPage:  user created
deactivate be
alt success
  LoginPage -> App: HandleGraphQLSuccess(response.createUser, dispatch, 'createUser')
  activate App

  App -> user: Alert user that they need to verify their email 
  deactivate App
else error
    LoginPage -> App: HandleGraphQLError(error, dispatch)
    deactivate LoginPage

    activate App

    App -> user: Alert user that there was an error

    deactivate App   
end

user -> em: click on link in email
activate em
em --> VerifyPage: navigate(/Verify?email={emailAddress}&token={validationToken})
deactivate em
activate VerifyPage
VerifyPage -> be: Verify user mutation
activate be
be --> VerifyPage: response
deactivate be
alt success
  VerifyPage -> App: HandleGraphQLSuccess(response.verifyUser, dispatch, 'verifyUser')
    activate App
  App -> HomePage: navigate(/)    
  App -> user: Alert user that they have successfully verified their email
    deactivate App
else error
    VerifyPage -> App: HandleGraphQLError(error, dispatch)  
    deactivate VerifyPage
    activate App
    App -> user: Alert user that there was an error  
    deactivate App
end

@enduml
